deps/uv.cmake

Can't really see how to check for Solaris using CMake, so the flags are here.
These flags are required to build libuv correctly.

add build flags for solaris

---

CMakeLists.txt
luv-1.4.2-1.rockspec

Add support for luarocks.
To release:
1. bump version number in rockspec filename and file contents.
1. tag `v1.4.2` in github
2. upload rockspec to  https://rocks.moonscript.org
See [Creating a rock](/keplerproject/luarocks/wiki/Creating-a-rock)

luarocks support.

---

src/fs_event.c

according to uvbook, http://nikhilm.github.io/uvbook/filesystem.html#file-change-events
```lua
local uv = require('luv')
if #arg==0 then
print(string.format("Usage: %s <command> <file1> [file2 ...]",arg[0]));
return
end
for i=1,#arg do
local fse = uv.new_fs_event()
assert(uv.fs_event_start(fse,arg[i],{
--"watch_entry"=true,"stat"=true,
recursive=true
},function (err,fname,status)
if(err) then
print("Error "..err)
else
print(string.format('Change detected in %s',
uv.fs_event_getpath(fse)))
for k,v in pairs(status) do
print(k,v)
end                
print('file changed:'..(fname and fname or ''))
end
end))
end
uv.run('default')
uv.loop_close()
```

fix bug in fs_event_start callback, file fs_event.c

---

CMakeLists.txt
Makefile
cmake/Modules/FindLibuv.cmake
cmake/Modules/FindLuaJIT.cmake

Add cmake options `WITH_SHARED_LIBUV` and `WITH_SHARED_LUAJIT` to locate and link against a shared libuv resp. LuaJIT library.
You can use the these options with make:
```WITH_SHARED_LIBUV=ON WITH_SHARED_LUAJIT=ON make```
Based on the wiki *CMake:How To Find Libraries*:
http://www.cmake.org/Wiki/CMake:How_To_Find_Libraries

Add shared linking options

---

src/fs.c
src/handle.c
src/luv.h
src/misc.c
src/stream.c
src/thread.c
src/udp.c

- add function luv_check_buf() to avoid warnings in MinGW (convert DWORD* to size_t*)
- avoid MinGW warnings that defined macros (S_IS* macros)
- change luaL_checkint to luaL_checkinteger
- use lua_getglobal() instead LUA_GLOBALSINDEX
some improves againest #147

Make luv compatible with Lua5.3

---

deps/uv.cmake

uv.lib(util.obj) : error LNK2019: 无法解析的外部符号 __imp__GetUserProfileDire
ctoryW@12，该符号在函数 _uv_os_homedir 中被引用 [E:\developing\c\luvi\build\luvi.vcxproj
]

Userenv.lib is missing in the uv.cmake

---

src/process.c

* The close callback happens after the endgames, so it is safe to
destroy

process: cleanup the lua handle in the close callback

---

CMakeLists.txt
cmake/Modules/FindLuaJIT.cmake

The search path for loading binary modules with the require function is
`LUA_ROOT "lib/lua/" LUA_VERSION_MAJOR "." LUA_VERSION_MINOR` on non-WIN32
targets.
Let us use this default path for installing the luv module. This allows the user to use
```lua
local uv = require('luv')
```
from every directory path.

Set correct installation path for luv module on non-WIN32 targets

---

src/thread.c

Old MSVC compilers do not support some C99 features. thread.c has some code before the varible declaration of the luaL_Buffer b.

Fix MSVC build

---

src/misc.c

Note that this is the "raw" mac address (not converted into <HEX><HEX>:... notation). The purpose of this change was to allow me to write an implementation of UUID generation (version 4): http://www.ietf.org/rfc/rfc4122.txt
...and for that purpose, having the "raw" mac address is more convenient.
However, if the project maintainer feels it would be better to have the "pretty" HEX notation, I can add the conversion code. Please just let me know.
Thanks,
-Brian

Add a "mac" field to the luv_interface_addresses().

---

.gitmodules

fix travis fail, because luajit can't access.

change luajit submodule url to https://github.com/LuaJIT/LuaJIT.git

---

.ci/install.bat
.ci/platform.sh
.ci/set_compiler_env.bat
.ci/setenv_lua.sh
.ci/setup_lua.sh
.ci/winmake.bat
.travis.yml
CMakeLists.txt
appveyor.yml
luv-1.8.0-0.rockspec
msvcbuild.bat
tests/test-dns.lua

Changes:
- Fix CMake policy warnings with CMake > 3.0
- Fix two problems with luarocks on Windows:
1. Defining the PREFIX var would prevent CMake from finding the MSVC compiler.
2. The luv module would always link with LuaJIT, instead of the Lua library used by LuaRocks.
- Add shell scripts to the `.ci` folder to install both Lua/LuaJIT and LuaRocks on AppVeyor and Travis.
- Add a LuaRocks "smoke test" to AppVeyor and Travis, where the `luv` rock is installed and then loaded, and the function `uv_cwd()` is called.
Some CI-related files have changed. It's now relatively easy to add multiple Lua/LuaJIT/MSVC versions to the continuous integration matrix, on both Travis and AppVeyor, thanks to the new CI scripts.
I only had one issue: in `tests/test-dns.lua` I had to disable the test at line …

Fix luarocks on Windows and add it to the continuous integration loop

---

src/constants.c
src/fs.c
src/luv.c
src/luv.h
src/poll.c
src/process.c
src/stream.c
src/work.c

This PR fixes nearly all of the warnings emitted by gcc with -Wall -Wextra.
Only warnings from the dependencies (which are unused parameter warnings) remain.
Fixes #197

Fix warnings

---

src/fs.c
tests/run.lua
tests/test-fs.lua
tests/test-timer.lua

Changes:
- Closes #201 (Change `fs_scandir_next()` to return two values instead of a table)
- Increase interval tolerance in test "timer - timeout with interval" in order to avoid random fails on AppVeyor and slow CI servers. Increased from 50ms to 100ms.

Change fs_scandir_next() to return two values instead of a table

---

src/process.c

Unfortunately if we always always create the stdio pipes as R+W (instead of only R for stdin, and only W for stdout and stderr) child processes on windows start to behave incorrectly. For example, if you spawn the 'cat' program, write to it and then shutdown its stdin, the correct behaviour is for the child to receive EOF and exit. But if stdin is RW the child never exits on Windows, and you have to kill the process to force it to exit. Changing the stdin pipe to only `UV_CREATE_PIPE|UV_READABLE_PIPE` fixes the problem.
The current solution assumes only the standard stdio fd's (0-2) are used. A more flexible solution may be in order, but would require an API change.

Fix incorrect behaviour on Windows related to stdio pipes being read-write

---

deps/luajit.cmake
tests/test-conversions.lua

* 64bit integer conversions do not work on Windows with 2.0.4
`29913653248` is converted to `0xf6fe2000`. Note: The low 32bits are correct, but the high 32 bits is missing. The correct answer is: `0x6f6fe2000`.
`32207650816` is converted to `0x7fb9c000`. The correct answer is `0x77fb9c000`.
Update: Luajit 2.1 does fix the issue on Windows.

bump to luajit 2.1

---

.travis.yml
appveyor.yml
bump.sh
luv-1.8.0-4.rockspec
rockspecs/luv-1.8.0-4.rockspec

This should make luv more compatible with luarocks echosystem:
- Doesn't depend on cmake(which may not be available). luv is very simple to
compile, and cmake is used more to setup dependencies, but this is already
taken care of by luarocks.
- Allows the user to specify custom libuv prefixes with LIBUV_DIR(which is the
idiomatic way of specifying dependencies location in luarocks)
- Respects CC
Close #223

Use luarocks native build on rockspec

---

deps/uv.cmake

This fixes linking errors when cross-compiling luv using MinGW.
A Unix filesystem backing userenv.lib file is case-sensitive.

uv.cmake: fix case of "userenv" library

---

deps/uv.cmake
src/dns.c

For #229, fix the uv.cmake recipe for OpenBSD and avoid using AI_ flags in systems where they are not available.
When loading the luv module you may still encounter an error. The workaround is to set LD_PRELOAD=/usr/lib/libpthread.so before calling the lua interpreter. I am still investigating this issue but AFAIK this also happens with other lua modules e.g.
http://openports.se/devel/lua-lgi

Build in OpenBSD

---

src/handle.c
src/lhandle.c

We need to make type checking more robust.  Currently closed handles don't count as handles and give unexpected type errors when calling methods like `handle:is_closing()` that are expected to be safe.

Make type checking for handles more robust. (#234)

---

rockspecs/luv-1.9.1-1.rockspec
src/async.c
src/lhandle.c
src/lthreadpool.h
src/thread.c
src/work.c
tests/test-async.lua
tests/test-conversions.lua

according to https://www.lua.org/manual/5.1/manual.html#lua_pcall, errfunc cannot be a pseudo-index.

fix error handle in callback with lua_pcall

---

src/luv.h
src/process.c

Define and use sparse_rawlen() for the stdio options passed into
process:spawn(). This fixes https://github.com/luvit/luv/issues/204

Fix #204: sparse stdio in process:spawn()

---

src/req.c

Fixes issue: 
https://github.com/luvit/luv/issues/257
NOTE: The documentation says cancel is implemented for a subset of request types:
http://docs.libuv.org/en/v1.x/request.html#c.uv_cancel
This change addresses some of the callbacks, but these probably also need to be changed to check for `UV_ECANCELED`:
- `luv_poll_cb()`
- `luv_connect_cb()`
- `luv_fs_event_cb()`
- `luv_fs_poll_cb()`
- `luv_shutdown_cb()`
- `luv_connection_cb()`
- `luv_write_cb()`
- `luv_udp_send_cb()`
We might want to also change the above functions so that the callbacks are not ran if `UV_ECANCELED` is the status. In light of the fact that the documentation claims cancel only works for a subset of types, not sure how critical it is avoid calling the callbacks when a request is canceled.
Thanks,
-Brian

Fix luv.cancel(req) so cleanup occurs in the callbacks

---

src/lhandle.c
src/lhandle.h

`pcall` (which is used to handle the actual calling of the callbacks) handles `__call` already, so the only thing blocking this was the `LUA_TFUNCTION` type check.
Example code that will now work:
```lua
local callable = setmetatable({}, {__call=function(...) print("called", ...) end})
callable()
pcall(callable)
local uv = require('uv')
local handle = uv.new_timer()
local delay = 0
uv.timer_start(handle, delay, 0, callable)
uv.run()
```
Which outputs:
```
called  table: 0x000d8420
called  table: 0x000d8420
called  table: 0x000d8420
```
Example error when trying to pass something non-callable as a callback argument:
```
bad argument #4 to 'timer_start' (function or callable table expected, got boolean)
```
(related: #265)

Allow callable tables as callback parameters (closes #265)

---

src/luv.h
src/tcp.c
src/udp.c

fixes #271 
The issue here is that parse_sockaddr was passed `addrlen`, the length of the input address, which passes it onto `uv_inet_ntop`. However, [`uv_inet_ntop`](https://github.com/libuv/libuv/blob/1a96fe33343f82721ba8bc93adb5a67ddcf70ec4/src/inet.c#L40-L48) expects the parameter to be the _maximum length of the output string_, not the length of the input address. The length of the input data is inferred from the value of `af`. Further proof in [inet_ntop6](https://github.com/libuv/libuv/blob/1a96fe33343f82721ba8bc93adb5a67ddcf70ec4/src/inet.c#L149-L151).
Thus `parse_sockaddr` doesn't actually need a `addrlen` passed to it at all, as the input address length is encapsulated in the `sockaddr` struct.

fix: address argument in read/recv callback is an uninitialized string when using IPv6 addr > 16chars long

---

src/udp.c

the udp_send function does not create a reference to the passed-in string or buffer. That means the Lua GC can and will garbage-collect the string and the write will result in an invalid memory access.

fix: reserve reference for buffer for udp send

---

CMakeLists.txt

Fixes CMake not looking for the Lua library when
the executable's name is not "lua".

Support versioned lua executable file.

---

.gitmodules
src/luv.h
src/thread.c

The unified and compatible interface uses lua-compat-5.3 implementation to reduce conflicts when All In One build in luvi.

use lua-compat-5.3 for standard APIs

---

examples/uvbook/thread-create.lua

The local `sleep` var in `hare_id` was assigned but never used. 
Tested this, works fine on macOS, although the field value is milliseconds, not seconds.

Use system sleep() function

---

Makefile
tests/test-dns.lua

close https://github.com/luvit/luv/issues/288
default `make` will use luajit amalg build, and `make WITHOUT_AMALG=YES` will not do amalg build.

fixup build

---

deps/luajit.cmake
deps/uv.cmake

These are required for building LuaJIT on OpenBSD with clang. They provide the symbols `_Unwind_*`.

Link the libraries libpthread and libc++abi

---

CMakeLists.txt
appveyor.yml

This caused a mismatch at link time between /MD and /MT. CMAKE_C_FLAGS and friends are directory-local but inherit from the current scope when add_subdirectory is called, so we need to make sure to modify them before any add_subdirectory calls
This should fix Windows builds.

Fix /MT linker flags not being inherited by libuv subproject (#297)

---

src/luv.c
src/misc.c

We do not export uv_get_osfhandle or uv_open_osfhandle yet...
Fixes: https://github.com/luvit/luv/issues/301

libuv: bump to 1.23.0

---

src/luv.c
src/luv.h

Exposing the compat-5.3.h header file directly in the luv.h header file
is not a good idea, because it causes redefinition errors when building,
for example latest luvi version 2.8.0, with a shared luv library and
LuaJIT 2.0.5.
Therefore, include the compat header file in the luv.c source file.
Note, that luvi version 2.8.0 still fails to build against the shared luv
library using LuaJIT 2.0.5, as it does use `luaL_newlib` which is not
available in Lua 5.1. However, this is unrelated to the luv library as
luvi itself should define the macro for Lua 5.1.

Do not include compat-5.3.h in luv header file

---

CMakeLists.txt

The correct way to check if an environment variable is defined is to use `if(DEFINED ENV{})`.
See: https://cmake.org/pipermail/cmake/2011-October/046704.html

Fix checking if environment variable is defined

---

src/poll.c

In order to use luv for reading GPIOs via sysfs with interrupt mode we have to use POLLPRI. This patch adds support for it and is tested on OpenWRT.

Added POLLPRI option to poll flags

---

src/udp.c
src/util.h

The error code will be properly translated in the next Libuv release, see https://github.com/libuv/libuv/issues/1978
Closes #306
EDIT: CI fail is unrelated, looks like an appveyor bug.

Fix luv_udp_recv_start error codes on Windows in Libuv <= 1.23.0

---

src/lhandle.c
src/luv.c
src/luv.h
src/process.c
src/stream.c
src/thread.c
src/udp.c
src/work.c

Ok, https://github.com/luvit/luv/issues/252 and https://github.com/neovim/neovim/pull/9546 hope luv use extern uv_loop_t created by other c libs. Let me try it.  please look at https://github.com/luvit/luv/commit/1241556cc5b6293a053b87ddaef4c01fe97e9922.
How to use.
1. create your uv_loop_t* loop out of luv.
2. call luv_set_loop(L, loop) before luaopen_luv.
3. call luvopen_luv, luvopen_luv will check wether need to create loop in luv. loop outside of luv will not be gc. so caller should manage it.

Try to support extern uv_loop_t

---

tests/test-dns.lua

Closes #340
This allows the full `make test` suite to run while offline.

Allow dns tests that require an internet connection to fail when offline

---

rockspecs/luv-scm-0.rockspec

This is required for LuaRocks to find libuv on Windows.
Ref: https://github.com/neovim/neovim/pull/10292#issuecomment-506924822
/cc @erw7

rockspec: LIBUV: specify library='uv'

---

CMakeLists.txt
Makefile
libluv.pc.in

This helps the development of other programs using LUV.
`make BUILD_MODULE=0 install` will install libluv.a and libluv.pc

Provide package config

---

src/process.c

Added UV_PROCESS_WINDOWS_HIDE_CONSOLE and UV_PROCESS_WINDOWS_HIDE_GUI flags in version 1.24.0

Add missed flags for uv_process_options_t

---

src/luv.c
src/luv.h

- Made luv_loop/luv_state ~~inline~~ functions instead of macros to make it more clear how they are meant to be used and give them type safety
- Updated the comments to match how things work now

Clean up luv_state/luv_loop/etc comments and API

---

src/lhandle.c
src/lhandle.h
src/lreq.c
src/util.c
src/util.h
tests/test-callbacks.lua

Follow up to #266, which made callable tables work for `luv_handle_t`, but accidentally forgot to apply the same thing to `luv_req_t`
Related: #265.

Fix callable tables as callback parameters for luv_req_t and add tests

---

src/luv.c

lua.h must be included before checking for LUA_VERSION_NUM otherwise we
won't get the version and compat-5.3.h will always be needed
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

src/luv.c: include lua.h

---

src/misc.c
src/util.c
tests/test-misc.lua

Without this patch, the added asserts in the test case would fail with:
```
tests/test-misc.lua:127: Unknown system error 0: Unknown system error 0
stack traceback:
[C]: in function 'assert'
tests/test-misc.lua:127: in function 'fn'
./lib/tap.lua:53: in function <./lib/tap.lua:42>
[C]: in function 'xpcall'
./lib/tap.lua:42: in function 'run'
./lib/tap.lua:136: in function <./lib/tap.lua:113>
[C]: at 0x00405680
not ok 18 uv.os_environ
```

Fix os_setenv/os_unsetenv returning an error when they succeed

---

lib/tap.lua

os.exit bypasses things like lua_close, so calling it on success makes it harder to evaluate if memory is getting leaked when tests pass

tap: Only call os.exit on failure

---

lib/utils.lua
tests/run.lua
tests/test-dns.lua
tests/test-process.lua
tests/test-signal.lua

`_G.isWindows` only gets set in tests/run.lua so running test-process.lua directly means `isWindows` would be nil on Windows

Fix some tests failing when run on their own on Windows

---

src/process.c
src/tcp.c
src/thread.c
src/udp.c

Went through all instances of `luv_newuserdata` to find things similar to #390 and fixed them all.
Before:
```lua
uv.new_thread() -- bad argument #1 to 'new_thread' (function expected, got userdata)
uv.spawn("", {}) -- bad argument #3 to 'spawn' (function or callable table expected, got uv_process)
uv.new_tcp("test") -- this would coerce the string into an int
uv.new_udp() -- this would always call uv_udp_init_ex and use the uv_udp_t userdata as the arg (coerced to 0)
```
After:
```lua
uv.new_thread() -- bad argument #1 to 'new_thread' (function expected, got no value)
uv.spawn("", {}) -- no error, 3rd argument is meant to be optional
uv.new_tcp("test") -- bad argument #1 to 'new_tcp' (number expected, got string)
uv.new_udp() -- this now correctly calls uv_udp_init instead of …
```

Fix various bugs with argument order/strictness/etc

---

src/fs.c

The `f_spare` field of `uv_statfs_t` is never initialized/used in Libuv, so it makes no sense to provide it to the user

fs_statfs: Fix pushing unused/uninitialized 'spare' values

---

src/tcp.c
src/udp.c

Allows specifying the address family as a string or an integer, consistent with how its specified in other luv bindings like getaddrinfo/getnameinfo
example:
```lua
uv.new_udp("inet")
uv.new_tcp("inet6")
```

Make new_tcp/new_udp first argument more user-friendly/consistent

---

tests/test-signal.lua

Use stdout to check that sigint was handled by the child process instead of the exit code of the child
This partially addresses #382 (see https://github.com/luvit/luv/issues/382#issuecomment-539765951). With this PR, LSAN does not detect any leaks during `tests/run.lua` for me.

Modify test-signal to avoid os.exit

---

appveyor.yml

This should cut the time it takes to run Appveyor CI in half (from ~50 minutes to ~25 minutes) and MSVC 2013 is old enough to stop running CI for I think (and even 2015 might be worth changing to 2017?).
EDIT: Related: https://github.com/luvit/luv/pull/344#issuecomment-515631371

Remove MSVC 2013 jobs from appveyor CI

---

src/tcp.c
src/udp.c

Closes #398
(was a false-positive)

Fix uninitialised var warning in new_tcp/new_udp

---

src/handle.c

Fixes #404  
Test:
```lua
local socket = uv.new_udp()
local size = 4096
local mult = jit.os == 'Linux' and 2 or 1
assert('udp bind', uv.udp_bind(socket, "0.0.0.0", 9123))
assert(uv.send_buffer_size(socket) == uv.send_buffer_size(socket, 0))
assert(uv.send_buffer_size(socket, size) == 0)
assert(uv.send_buffer_size(socket) == size * mult)
assert(uv.recv_buffer_size(socket) == uv.recv_buffer_size(socket, 0))
assert(uv.recv_buffer_size(socket, size) == 0)
assert(uv.recv_buffer_size(socket) == size * mult)
```
I'd say add this to the test suite, but the behavior is annoyingly platform dependent. The size can be silently doubled or clamped, so there's no strong guarantee on what happens. I thought libuv is supposed to iron this stuff out.
Libuv code for reference:
- …

Fixes returning of send/recv buffer size

---

src/loop.c

`uv_backend_fd` returns a bare -1 (not an error code) on Windows, so interpreting it as an error code is wrong. This is similar to how `luv_backend_timeout` is bound (which also can return a bare -1)
```lua
print(uv.backend_fd())
-- before
nil     Unknown system error -1: Unknown system error -1        Unknown system error -1
-- after
nil
```
This is just one simple way to fix this. Returning -1 doesn't feel like the best way to bind this, though. Open to suggestions (that we'd also apply to `luv_backend_timeout`)
EDIT: Now returns nil, see comments below.
Relevant comments:
- https://github.com/luvit/luv/pull/403#issuecomment-540273026
- https://github.com/luvit/luv/pull/403#issuecomment-540864344

Fix luv_backend_fd returning "Unknown system error" on Windows

---

src/tcp.c

It would just return whatever happens to be at the top of the stack (the last argument passed to tcp_close_reset), now it returns the result consistent with other functions
EDIT: To address a potential concern, the `lua_pop` was just a copy+paste artifact--it's not necessary
Related to comments in #409

Fix tcp_close_reset returning inconsistent values on success

---

src/pipe.c

From #399 
> `uv.new_pipe`'s `ipc` argument should probably be made optional (defaulted to false) rather than required

Make new_pipe ipc argument default to false

---

.travis.yml
CMakeLists.txt
Makefile
appveyor.yml
rockspecs/luv-scm-0.rockspec
src/luv.c

This better matches how it would be found when building against system-installed lua-compat53.
---
I realize there's not a _ton_ of precedence here, since a lot of packages simply vendor lua-compat53, but Debian's [codesearch](https://codesearch.debian.net/search?q=compat-5%5C.3%5C.h+-pkg%3Alua-compat53+-path%3A.*compat-5%5C.3%5C.c&literal=1) shows a general trend.

Remove c-api directory from #include for compat-5.3.h

---

lib/tap.lua

Second optional argument to os.exit is a boolean that determines if lua_close should be called while exiting. This was added in PUC Lua 5.2 and backported to LuaJIT.
This allows the tests to provide accurate memory leak information even with failing tests (memory leak info will still be inaccurate with failing tests on PUC Lua 5.1, since PUC Lua 5.1 os.exit bypasses lua_close).
Thanks to @vanc for the fix, see https://github.com/luvit/luv/issues/382#issuecomment-546032911

tap: Make os.exit call lua_close on Lua versions that support it

---

README.md
docs.md

First pass at improving docs.md.
Closes #118
Closes #144
Closes #378
This is a total rewrite so the diff might be overwhelming. Sorry that it's all one big commit. Since the previous version, I cleaned up or expanded the existing sections and added:
- Error handling
- Version checking
- uv_fs_event_t
- uv_fs_poll_t
- File system operations
- Thread pool work scheduling
- DNS utility functions
- Threading and synchronization utilities
- Miscellaneous utilities
TODO
- ~~New change; haven't had a chance to look at it.~~ 
- ~~This is the first error function exposed to Lua, so I'm not sure what this is doing here.~~
- ~~We only expose `uv_cancel` but we might want to document which subtypes are `uv_req_t` and which ones can be canceled.~~ (See #416)
- ~~This isn't a libuv function, so I'm not …

Update and expand docs

---

Makefile

- Adds BUILD_DIR config option
- Adds BUILD_TYPE config option (i.e. Release, Debug, etc).
+ Default set to RelWithDebInfo.
+ Closes #425
---
Not sure what the default build type should be here. If anyone has any reasoning for choosing one over another, let me know.

Fix Makefile passing build type too late and some other improvements

---

src/fs.c
src/lreq.c
src/lreq.h
src/luv.h
src/misc.c
src/stream.c
src/udp.c
tests/test-fs.lua
tests/test-udp.lua

Part of #397
luv_req_t now stores either one or multiple refs to the strings passed to functions that use uv_buf_t. This fixes those strings possibly being garbage collected between the time the uv_buf_t is constructed and the time the send/write actually completes. See https://github.com/luvit/luv/issues/397 for a more complete explanation of the problem.
- Introduces a constant called `LUV_REQ_MULTIREF` which is an arbitrary negative value that luaL_ref will never return that signifies that `luv_req_t.data` is a `LUA_NOREF`-terminated array of `int`s and handles that case accordingly in `luv_cleanup_req`. This might be more hacky than it needs to be but it makes it possible to leave the structure of `luv_req_t` unchanged.
- Maintains backwards compatibility in that it will still coerce …

Handle uv_buf_t passed to write/send functions properly

---

src/luv.c
src/work.c

1. To avoid undefine…d behavior in libuv and luajit follow https://github.com/luvit/luv/commit/7526c1d9955f085df9eb1c25fcc31c0cfe67e583.
2. Replay https://github.com/luvit/luv/issues/433.
3. LUVF_CALLBACK_ flags introduced by https://github.com/luvit/luv/commit/5b68007d6919edd2f5c99830ba0679f958b1235c#diff-4221738e9478598ca8f06be66d888559

Hard exit on pcall failed

---

examples/talking-to-children.lua

The problem is that the shutdown callback is being called during loop_gc, so the Lua/Libuv state is being closed/free'd and the `handle` local var has already been closed/free'd so it's no longer a valid uv_stream_t (see https://github.com/luvit/luv/pull/414).
This will fix PROCESS_CLEANUP_TEST but there is more to do to solve the general case of 'things happening during loop gc'

Quick fix for PROCESS_CLEANUP_TEST CI failures

---

.ci/bindcov.sh
.ci/lsan_build.supp
.travis.yml
src/fs.c
tests/manual-test-leaks.lua
tests/test-sigchld-after-lua_close.sh

Still a work-in-progress. Once finished, will close #395.
+ [x] Need to intentionally introduce a leak/error to make sure Valgrind catches it (https://travis-ci.org/luvit/luv/builds/605741562)
+ [x] Need to intentionally introduce a leak/error to make sure LSAN/ASAN/UBSAN catches it (https://travis-ci.org/luvit/luv/builds/605741562)
- Also closes #428 and closes #429
---
EDIT: Note that right now the ASAN and Valgrind checks use PUC Lua 5.3. I did that because it's simpler to get working (see https://github.com/luvit/luv/issues/382#issuecomment-539765951) and any errors should be less cryptic, but it might be better to check against LuaJIT instead since that's what `luv` is used with most of the time.

Travis CI improvements (Valgrind/ASAN/etc)

---

tests/test-tcp.lua

test-tcp: Skip tcp_close_reset tests with Libuv < 1.32.0

---

.travis.yml

Fixes https://github.com/luvit/luv/issues/382#issuecomment-549249061, see https://github.com/libuv/libuv/issues/727

travis: Fix Valgrind detecting false-positive leaks in child when uv_spawn fails

---

src/dns.c

The `curr` variable is set in the head of the loop, so there is no need to assign it before the loop.

don't assign unnecessarily

---

.travis.yml

This fixes the issue described in #446 but the CI is still failing due to
```
lj_err.c:290:8: error: thread-local storage is not supported for the current target
static __thread _Unwind_Exception static_uex;
^
```
caused by https://github.com/LuaJIT/LuaJIT/commit/44382e833a9334c19e47e64e8078a322026e094d
Not sure how to fix that. Need someone more familiar with OSX to look into it. @zhaozg ?

travis: Default MACOSX_DEPLOYMENT_TARGET to 10.4 for LuaJIT 2.1

---

deps/luajit.cmake

Addresses the "'fold_hash' undeclared" compile errors in https://github.com/luvit/luvi/issues/225
See also https://github.com/torch/luajit-rocks/issues/39

LuaJIT: Fix WITH_AMALG option failing during parallel builds

---

src/lreq.c

Since commit 3e34390cc15101d7fc46ea26f5adf9ac022c2029, build fails with gcc 4.8.3 on:
```
In file included from /usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-0/output/build/luv-1.34.1-1/src/luv.c:27:0:
/usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-0/output/build/luv-1.34.1-1/src/lreq.c: In function 'luv_cleanup_req':
/usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-0/output/build/luv-1.34.1-1/src/lreq.c:70:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (int i = 0; ((int*)(data->data))[i] != LUA_NOREF; i++) {
^
```
Fixes:
- http://autobuild.buildroot.org/results/83b34e606b128546da8a70836d039090e334a1ec
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

src/lreq.c: fix build with gcc 4.8

---

CMakeLists.txt

@zhaozg this is a followup to https://github.com/luvit/luv/pull/459#issuecomment-592446703
---
This adds on to the changes in https://github.com/luvit/luv/pull/459 to make it possible to build module, static, and shared libraries all at the same time if requested
- To build the module, `-DBUILD_MODULE=On`; the target name for the module is `luv`
- To build a static library, `-DBUILD_STATIC_LIBS=On`; the target name for the static lib is `libluv_a` (this matches how `libuv` names its targets [`uv` for shared and `uv_a` for static])
- To build a shared library, `-DBUILD_SHARED_LIBS=On`; the target name for the shared lib is `libluv`
These are able to be mixed/matched as needed.
This is a breaking change (as was #459) for users of CMake (e.g. luvi) who will now need to specify linking …

CMake: Add BUILD_STATIC_LIBS option

---

CMakeLists.txt

Fixes #463
@teto let me know if this fixes the problem for you.

CMake: Fix header install paths for shared/static builds when using LuaRocks

---

lib/tap.lua
lib/utils.lua
src/dns.c
src/fs.c
src/luv.c
src/misc.c
src/pipe.c
src/poll.c
src/tcp.c
src/udp.c
tests/test-callbacks.lua
tests/test-dns.lua
tests/test-fs.lua
tests/test-misc.lua
tests/test-tcp.lua
tests/test-thread.lua
tests/test-udp.lua

This has been tested against Libuv 1.0.0 on Linux and it now compiles and all tests now pass with that setup. No other intermediate versions were tested, though.
Fixes #473, contributes towards #474. The next step would be to start testing against Libuv 1.0.0 in CI.
---
https://github.com/luvit/luv/commit/e431c70b5b37f4a9b3081c24c2da90dc69b8d85b is of particular note.
Skipped test lines now look like:
`ok 102 udp - udp connect # skip Requires libuv >= 1.27.0`
Final output line looks like (when there are skipped tests):
`# All tests passed (33 skipped)`

Make Luv work with Libuv versions all the way back to 1.0.0

---

.ci/setup_min_libuv.sh
.travis.yml

This should allow us to catch any accidental introductions of breaking changes with earlier libuv versions
Closes #474

Add a test phase for compiling against libuv 1.0.0

---

.ci/setup_lua.sh

I'm kind of hoping this might fix the random CI failures when downloading LuaRocks source tars mentioned [here](https://github.com/luvit/luv/pull/479#issuecomment-614509413), but using `https` urls makes sense anyway.

CI: setup_lua: use https for source tar downloads

---

.ci/setup_lua.sh

This seems to fix the occasional failures. I restarted [this build](https://travis-ci.org/github/squeek502/luv/builds/675931212) a few times and it passed every time.

CI: Retry connection to luarocks.org to workaround occasional timeouts

---

docs.md
src/fs.c
tests/test-fs.lua

The magic -1 was not very user friendly and wasn't documented, and making it an optional argument makes the most sense to me. This is fully backwards compatible, and will also error on cases where the offset could be used as a callback, but the user probably didn't intend it to be the callback, like:
uv.fs_read(fd, 32, function() end, function() end)
which will give the error
bad argument #3 to 'fs_read' (number expected, got function)

fs_{read,write}: make offset argument optional and default it to -1

---

.ci/bindcov.sh
.ci/libuv2840.supp
.travis.yml
docs.md
src/luv.c
src/udp.c
tests/test-udp.lua

- Allows the interface argument of udp_set_membership to be nil (meaning a NULL const char* passed to uv_udp_set_membership). This was needed to be able to port the libuv multicast join tests
- Adds a binding for udp_set_source_membership (contributes towards #410)
- Ports the test-udp-multicast-join and test-udp-multicast-join6 tests from libuv
---
Note that the added test cases might not be portable. Libuv has some special handling for specific platforms that hasn't been ported to luv:
- https://github.com/libuv/libuv/blob/55dede5b6f730882d79f994138f0f23a7b28b119/test/test-udp-multicast-join.c#L129-L132
- https://github.com/libuv/libuv/blob/55dede5b6f730882d79f994138f0f23a7b28b119/test/test-udp-multicast-join6.c#L33-L44
EDIT: These might be solved by …

udp: Add udp_set_source_membership binding + improve udp_set_membership

---

docs.md
src/handle.c
src/luv.c
src/req.c
tests/test-handle.lua
tests/test-req.lua

- `handle_get_type`: Provides the functionality of both uv_handle_get_type and uv_handle_type_name in one function. Contributes towards #410
- `req_get_type`: Provides the functionality of both uv_req_get_type and uv_req_type_name in one function. Contributes towards #410
- Also adds method form of uv.cancel: req:cancel(). Contributes towards #416

Add handle_get_type and req_get_type

---

docs.md
src/loop.c
src/luv.c
src/private.h

Contributes towards #410, implements #103
There's no test case added because it would affect the loop for all other tests (there's no way to undo `"block_signal", "sigprof"` once it's set). I did make sure that `uv.loop_configure("block_signal", "sigprof")` succeeds on Linux, though.

Add loop_configure binding

---

src/luv.c
src/private.h

Building using the new Lua 5.4 version fails due to the included file `compat-5.3.h`

Update Lua version check

---

src/process.c

Fixes compilation when not using C99 or newer. See https://github.com/luvit/luv/pull/511#issuecomment-685473576

Remove initial declaration in for loop

---

.travis.yml

This should allow us to catch otherwise hard-to-reproduce bugs where things can sometimes be garbage collected before they are used, like https://github.com/luvit/luv/issues/507 and https://github.com/luvit/luv/issues/510
Closes #510

Tune garbage collector to be extremely aggressive during Valgrind/ASAN tests

---

docs.md
src/loop.c
src/luv.c
src/luv.h
tests/test-loop.lua

Closes #498.
I originally wrote a `loop_running` function, but thought that returning the mode is potentially more useful than just `true/false`, so wrote this instead.
Note that`ctx->mode` has to be initialized to `-1` for this to work as expected. That's a potential point of failure, but I think it will be okay.

Adds uv.loop_mode function

---

docs.md
src/udp.c
tests/test-udp.lua

See the added comment for my thought process here:
https://github.com/luvit/luv/blob/43fb1183d4599e06ad85df1fc8a4b2782f35a0c4/src/udp.c#L48-L57
Submitting this as a draft because there's still some more things to be figured out:
- There are some bugs that need to be worked out with UV_UDP_RECVMMSG enabled, some of the udp tests are failing
- I think the usefulness of `recvmmsg` depends on the buffer size, which we don't give Lua control of (we use the `suggested_size` from [uv_alloc_cb](http://docs.libuv.org/en/v1.x/handle.html#c.uv_alloc_cb)). Maybe turning on `UV_UDP_RECVMMSG` only makes sense if we also allow changing the size of the recv buffer.
- The parameter of `luv_new_udp` is a little bit strange now, I think we might want to allow it to be passed as a table and have different …

luv_new_udp: Add support for UV_UDP_RECVMMSG

---

src/work.c

In thread pool, args passed to work callback maybe gc, use LUVF_THREAD_MODE_ASYNC flags to avoid.

fix a memroy bugs in thread pool work callback

---

src/lhandle.c

```data``` is not freed in the default (error) branch.
Thanks,

Fix possible memory leak in lhandle.c

---

src/misc.c

`uv_cpu_info` Gets information about the CPUs on the system.
The cpu_infos array will have count elements and needs to be freed with uv_free_cpu_info().
`uv_free_cpu_info` should be called when get cpu info fail.
I found this bug when enable AddressSenilizer, when handle:close() for uv_cpu_info.
```
=================================================================
==26121==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 336 byte(s) in 7 object(s) allocated from:
#0 0x101d4edc2 in __sanitizer_mz_calloc+0x92 (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x46dc2)
#1 0x7fff20171eb6 in _malloc_zone_calloc+0x3a (libsystem_malloc.dylib:x86_64+0x1beb6)
#2 0x7fff203ac180 in _CFRuntimeCreateInstance+0x124 (CoreFoundation:x86_64h+0x4180)
#3 0x7fff203ab906 in …
```

fix memleaks in luv_cpu_info

---

src/fs.c
tests/test-fs.lua

Output of the added test, before (note that the relevant path for each of these errors messages is actually the destination, not the source):
```
"fs_rename"	"EISDIR: illegal operation on a directory: luv7TbDmb"
"fs_link"	"EEXIST: file already exists: luv7TbDmb"
"fs_symlink"	"EEXIST: file already exists: luv7TbDmb"
"fs_copyfile"	"EISDIR: illegal operation on a directory: luv7TbDmb"
```
After:
```
"fs_rename"	"EISDIR: illegal operation on a directory: luv7TbDmb -> luvQzLgbb"
"fs_link"	"EEXIST: file already exists: luv7TbDmb -> luvQzLgbb"
"fs_symlink"	"EEXIST: file already exists: luv7TbDmb -> luvQzLgbb"
"fs_copyfile"	"EISDIR: illegal operation on a directory: luv7TbDmb -> luvQzLgbb"
```

fs: Print destination paths in error messages for the relevant functions

---

docs.md
src/fs.c
src/private.h
src/util.c

- Callback for the async version can be given as the 3rd parameter if the flags argument is omitted
- Flags can be specified as either a table, an integer, or nil, and will throw an error for unexpected types
Closes #529

Make symlink/copyfile bindings more user-friendly

---

CMakeLists.txt

All tests pass after running `make test`.
Closes #527.

Fix shared library build failure on macOS

---

docs.md
src/constants.c
src/dns.c
src/private.h

Follow up to https://github.com/luvit/luv/pull/534#issuecomment-821902777
The `Get all adresses for luvit.io` test in `test-dns.lua` now gives:
```
{ addr = "206.189.225.172", family = "inet", protocol = "tcp", socktype = "stream" },
{ addr = "206.189.225.172", family = "inet", protocol = "udp", socktype = "dgram" },
{ addr = "206.189.225.172", family = "inet", protocol = "ip", socktype = "raw" },
{ addr = "2604:a880:400:d0::1b9f:2001", family = "inet6", protocol = "tcp", socktype = "stream" },
{ addr = "2604:a880:400:d0::1b9f:2001", family = "inet6", protocol = "udp", socktype = "dgram" },
{ addr = "2604:a880:400:d0::1b9f:2001", family = "inet6", protocol = "ip", socktype = "raw" }
```
which has the correct protocols.
---
Protocol hinting also works, e.g.
```lua
local uv = require('luv') …
```

Fix protocol being treated as family in getaddrinfo inputs/outputs 

---

src/luv.h

Even for non-MinGW builds, the macros may already be defined (e.g., by other code in the project using luv).
Defining them whenever they do not exist handles both build types and also avoids lots of compiler warnings when they already exist in non-MinGW environments.

Only define S_IS... macros if they are not defined

---

tests/test-udp.lua

This is one way to close #539. See https://github.com/luvit/luv/issues/539#issuecomment-835188694 for a bit more context.
With the default settings of `firewalld` (used by Fedora, RHEL, etc), incoming messages from multicast IPs are dropped, meaning that the multicast test will hang forever. This PR introduces a 1 second timeout, after which the test will fail.
When the tests timeout, it'll look something like:
```
timeout (could be caused by firewall settings)
.\lib/tap.lua:66: Found 1 unexpected call
stack traceback:
[C]: in function 'error'
.\lib/tap.lua:66: in function <.\lib/tap.lua:48>
[C]: in function 'xpcall'
.\lib/tap.lua:48: in function 'run'
.\lib/tap.lua:146: in function <.\lib/tap.lua:122>
[C]: at 0x7ff7494359f0
not ok 6 udp multicast join ipv4
timeout (could be caused by …
```

Add timeout to udp multicast join tests

---

CMakeLists.txt
luv-scm-0.rockspec

LuaRocks can provide LUALIB and LUA_LIBDIR variables which should be better than trying to find the right library file ourselves.
Note: it does not provide them if the LuaRocks config setting `link_lua_explicitly` is false, so LuaRocks will give the following warnings in that case:
Warning: unmatched variable LUALIB
Warning: unmatched variable LUA_LIBDIR
These warnings happens on Linux and Mac, since they don't link against the Lua libraries. I'm not sure if there's a clean way to avoid the warnings.
Attempts to address #523.

rockspec: Use library file given by LuaRocks instead of trying to find it ourselves

---

.ci/setup_lua.sh
src/thread.c

luaL_buffinit apparently can push things onto the stack (although this is undocumented in the Lua 5.4 manual), so it needs to be called after lua_dump to make sure the function to-be-dumped is still at the top of the stack in lua_dump
Closes #553

Fix thread dumping in Lua 5.4.3+

---

.github/workflows/ci.yml

Follow up to #551
- Only run on tagged commits
- Should behave the same as it did on Travis
- Needs LUAROCKS_API_KEY set as a secret for the repository: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

Add deploy step to Github Actions

---

.ci/docscov.sh
.github/workflows/ci.yml
docs.md

Adds a docscov.sh script that runs in CI to check `luv.c` against `docs.md` to see if there are any functions that are defined in luv.c but not documented in docs.md. Compliments the existing bindcov.sh and will help make sure we document any newly bound functions in the future.
Also updates `docs.md` to fix all the undocumented functions that docscov.sh initially found.

Add docs coverage script + fix documentation using what it found

---

src/lhandle.c
src/loop.c
src/lreq.c
src/luv.c
src/luv.h
src/thread.c
src/work.c

If an error occurs in the entry function of a thread, the main thread will also exit if the entry function is not running in protected mode. For software that incorporates `luv`, such as `neovim`, this behavior is fatal. This PR adds `luv_set_thread` so that the thread entry function can be executed in the custom function as well as the `callback`.

Add function to run thread in protected mode

---

src/luv.c
src/luv.h
src/private.h
src/thread.c
src/work.c
tests/test-work.lua

This is an attempt to fix #564 with a different approach than #565.
Change `luv_work_cb()` to run in protected mode and throw an error in `luv_thread_arg_set()` if an argument of an impermissible type is passed. It's a little more complicated, but I've integrated it into `neovim` and it seems to be working.

fix #564, invalid thread argument causes crash.

---

src/async.c
src/check.c
src/dns.c
src/fs.c
src/fs_event.c
src/fs_poll.c
src/idle.c
src/misc.c
src/pipe.c
src/poll.c
src/prepare.c
src/process.c
src/signal.c
src/stream.c
src/tcp.c
src/timer.c
src/tty.c
src/udp.c

avoid to re-compile luv when upgrade libuv in the future

use uv helper to get handle/request struct size

---

src/lthreadpool.h
src/luv.c
src/thread.c
src/work.c

use uv_key_t to do thread local storage, and get better performance.

simplify vm management in thread and threadpool

---

.ci/install.bat
.ci/set_compiler_env.bat
.ci/setup_lua.sh
.github/workflows/ci.yml
appveyor.yml
msvcbuild.bat

This essentially treats MSVC 2015 as the minimum supported version, and updates the Appveyor CI to use MSVC 2022 to do all the Lua/Luarocks tests. From #586:
> I'm thinking about keeping the current 2015 tests, and then moving the rest to just use 2022. That way we can ensure we maintain a minimum supported MSVC (2015) and ensure that we build using the latest version. We won't ensure that the in-between versions will still build properly, but it seems somewhat unlikely that we would introduce problems specific to an in-between version.
Closes #586

CI: Use MSVC 2022 and update Lua/Luarocks versions

---

src/misc.c

In Libuv 1.44.0, uv_passwd_t.uid/gid was changed to be unsigned, so the >= 0 check would always return true. Changing to compare against -1 explicitly fixes #589 while still maintaining correct functionality when built against previous Libuv versions. Note that with Libuv 1.44.0 and above, this relies on implicitly casting -1 to unsigned long (the type of `uv_passwd_t.uid`/`uv_passwd_t.gid`).
Before (incorrectly including `uid`/`gid`):
```
{ homedir = "C:\\Users\\Ryan", username = "Ryan", uid = 4294967295, gid = 4294967295 }
ok 13 uv.os_get_passwd
```
After (correctly omitting `uid`/`gid`):
```
{ homedir = "C:\\Users\\Ryan", username = "Ryan" }
ok 13 uv.os_get_passwd
```

os_get_passwd: Explicitly compare uid/gid against -1 instead of >= 0

---

src/misc.c

-1 only has special meaning on Windows, and gid and uid are always set to -1 on Windows, so we can just omit the gid and uid fields on Windows instead of checking for -1. This is a better fix for #589, and a follow up to #590.
See also https://github.com/libuv/libuv/pull/3476#issuecomment-1065822945

os_get_passwd: Fix potential omission of gid/uid values in non-Windows environments

---

.github/workflows/ci.yml
appveyor.yml
luv-scm-0.rockspec
rockspecs/luv-scm-0.rockspec

I think this might drop support for Luarocks earlier than 3.0, but not totally sure. Closes #592

Add `luarocks test` support

---

docs.md
src/fs.c
tests/test-fs.lua

If opendir/closedir was called in a loop, it was possible for the uv_dir_t pointer to always be the same between calls, and due to how we kept track of the 'closed' state of the uv_dir_t by its pointer, this could lead to freeing things twice, or freeing the memory before a readdir call, etc.
Instead, we now use a wrapping luv_dir_t and normal Lua references to keep track of the state
Fixes #597

opendir and friends: Fix race condition when uv_dir_t pointer doesn't change between allocations

---

src/fs.c
tests/test-fs.lua

See commit messages and #603 for more info.
The added test is unrelated to the segfaults, but it's worth making sure that the async version of `fs_scandir` works, which we didn't have a test for previously.

Fix two possible `fs_scandir` segfaults

---

tests/test-fs.lua

Follow up to #605 and #603. The sync error test added here was the actual cause of the segfaults in normal usage.
See https://github.com/luvit/luv/issues/603#issuecomment-1148182526 for more context.

Add tests for fs_scandir errors

---

src/poll.c

This line has been there for quite a while :) 
I just noticed the log messages when building a libmosquitto wrapper around the poll handle and wondered where it came from.

Removed output to stderr from poll callback

---

deps/luajit.cmake

For reference, this is the logic we're trying to copy from LuaJIT's makefile:
https://github.com/LuaJIT/LuaJIT/blob/03080b795aa3496ed62d4a0697c9f4767e7ca7e5/src/Makefile#L339
---
Previously, CMake would only read up to the first NUL or control character (for me that meant it would only read "ELF" from tmpunwind.o). This was making CMake think there was no `eh_frame`/`__unwind_info` string in the file even if there actually was one.
Now, CMake skips binary data in tmpunwind.o and just reads all the ASCII strings from the file, which is fine for what we need to do with it.
This fixes:
In file included from luv/deps/luajit/src/ljamalg.c:23:
luv/deps/luajit/src/lj_err.c: In function ‘lj_err_unwind_dwarf’:
luv/deps/luajit/src/lj_err.c:469:2: error: #error "Broken build system -- only use the …

Yet another luajit.cmake unwind detection fix

---

docs.md

documents changes introduced in https://github.com/luvit/luv/commit/a817184ef450bc31702db8e03cefc7ee67878624

docs: document uv.errno

---

README.md

Someone must've been writing a lot of JavaScript when they wrote this code. Just removed the semicolon and also decided to remove the whitespace after the print to keep things consistent.

Remove unnecessary whitespace and semicolon

---

src/fs.c

MINGW64 defines stat and fstat to _stat64 and _fstat64 respectively, which is applied globally. This breaks the FS_CALL macros by replacing uv_fs_stat with uv_fs__stat64 and uv_fs_fstat with uv_fs__fstat64 (those obviously don't exist).
Fixes #624

Modify the FS_CALL macros to fix MINGW64 builds

---

src/fs.c
src/luv.h
src/private.h
src/thread.c
src/work.c

Fixed several compile warnings regarding Wshadow and Wstrict-prototypes.
luv/src/fs.c:431:14: warning: declaration of ‘data’ shadows a previous local [-Wshadow]
luv/src/private.h:114:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
Signed-off-by: Xu Xingliang <xuxingliang@xiaomi.com>

Fix compile warnings.

---

src/handle.c
src/stream.c

Fixes #633.
Is the style I used here OK? It felt kind of different than the rest of the code, the assignments in the if statements more specifically..

fix segfault in luv_check_handle/luv_check_stream

---

docs.md

`new_thread` already had this documented, although the argument type was missing `or string`, it also implied that only bytecode is accepted which seems to be inaccurate, as Lua code is accepted too  (internally it just `load`).
The same applies to `new_work`.

docs: new_work & new_thread string argument

---

docs.md

I believe this should be a `poll` not an `event`.

[docs] Correct parameter typed as uv_fs_event_t

---

docs.md
src/thread.c
tests/test-thread.lua

close https://github.com/luvit/luv/issues/636

fix thread arguments limit

---

docs.md

There seems to be a problem if the `luv_thread_t userdata` is released before the thread terminates. I have confirmed that the thread entry function may not be executed because `thd->code` was released by `gc` as shown below by the debugger. I have not been successful in creating a test case. An example of a segmentation fault in `luv_thread_arg_clear`, possibly due to this issue, has been reported in the neovim issue(neovim/neovim/issues/22694).
```lua
local uv = require'luv'
uv.new_thread(function()
print('Hello')
end)
collectgarbage('collect')
-- wait for thread to finish
uv.sleep(3000)
```
```
> gdb luajit
…
>>> break luv_thread_gc
…
>>> commands
>p "call luv_thread_gc"
>cont
>end
>>> break luv_thread_cb
…
>>> commands
>call sleep(1)
>p "call luv_thread_cb"
>p …
```

doc: update for new_thread note

---

src/constants.c

fs_access is equivalent to access(2), but this function is useless without the corresponsing access mode constants F_OK, R_OK, W_OK, and X_OK. Let's add these constants to the table.

Add access(2) constants to the constants table

---

src/constants.c
src/tty.c
tests/test-tty.lua

https://github.com/luvit/luv/issues/399

chore: update uv.tty_set_mode, and add tty test

---

src/handle.c
src/lhandle.c
tests/manual-test-exit.lua
tests/manual-test-without-uv.run.lua
tests/test-loop.lua

Fix https://github.com/luvit/luv/issues/599
Fix part of https://github.com/luvit/luv/issues/437

chore: fix crash in `loop_gc`

---

src/luv.c
tests/manual-test-cb-non-string-error.lua

update for https://github.com/luvit/luv/issues/663

fix: callback handle error with non-strings

---

docs.md

In Libuv, [uv_process_kill](https://docs.libuv.org/en/v1.x/process.html#c.uv_process_kill) takes a process and a signum, where the signum is required. In Luv although, in luv_parse_signal, if the input is not an integer and not a string, the default value of SIGTERM is used.
Effectively making signum an optional argument with the default string value `sigterm`.

docs: make process_kill signum arg optional

---

docs.md

uv.os_unsetenv takes a name parameter.
📝 code
https://github.com/luvit/luv/blob/8ca04df069eb837a725af1f02e4b5a59bb1ae7ef/src/misc.c#L498-L506

docs: add missing uv.os_unsetenv() parameter

---

docs.md

same as https://github.com/luvit/luv/pull/666/ for the same reasons.
See https://github.com/luvit/luv/blob/9e3c2320149884e5d809e9391f8580bb5f67bcdf/src/process.c#L319-L324

docs: make uv.kill's signum optional

---

docs.md

This was left over from the libuv docs, but the luv bindings handle this differently and `options.args` should *only* include the command arguments, not the command name itself.
See https://github.com/luvit/luv/issues/673#issuecomment-1703780666
Example from our tests:
https://github.com/luvit/luv/blob/dcd1a1cad5b05634a7691402d6ca2f214fb4ae76/tests/test-process.lua#L14-L31

docs: Correct uv.spawn `options.args` docs about the first argument

---

CMakeLists.txt

Remove redundant CMake policy change

---

docs.md

From what I can see, the callback argument is not optional and can't be nil.
See https://github.com/luvit/luv/blob/master/src/async.c#L38.
I can't be 100% sure that the docs are wrong here and not the code itself for not allowing optional callbacks, but I can't see why would anyone need to create an async handle with no callback as that is counterintuitive.

docs: new_async callback is not optional

---

docs.md

the field name is `no_truncate` not `no_trunate`, it is correctly defined in the code.
I think the `true|false` format is also inconsistent, it will make things harder when generating the docs, should simply be something like `{ no_truncate: boolean }`, or the more consistent
```md
`flags`:
`no_truncate`: `boolean`
```
update:
There is also a new `**Note**` format that was introduced with https://github.com/luvit/luv/commit/8e2f3066f9e999affa668f1dabe633e418b0cefd.
But maybe I will tackle those later when I progress with https://github.com/Bilal2453/luv-docgen.

docs: typo in a table field name

---

docs.md

Since I've used this docs to generate my luvit-meta definitions, which will complain about not using `assert` on methods that could return `nil` (on failure), I've had to investigate into things like `local pipe = uv.new_pipe()` not using an assert in the examples.
And it appears like it and the methods listed below will never return a failure tuple when initializing a new handle.  Even though the docs here explicitly imply otherwise as the return type is `handle_type or fail`.
Here are the details and how I came to the conclusion that each one of the methods patched don't return an error:
- `new_prepare` and `new_check` and `new_idle`: 
- on Luv side:
- in Luv those are `luv_new_prepare` etc.
- they make a call to `uv_prepare_init` (and `uv_check_init` and `uv_idle_init`).
- a failure is …

docs: most new_handle methods won't return fail

---

tests/test-tty.lua

Closes #687
@cryptomilk can you confirm that this fix will work for you?

test-tty: Don't depend on stdin/stdout handle type

---

.gitmodules

I'm working on an experiment to make submodules easier to work with.  Part of that is annotating .gitmodules with information to make it so tools can automatically update dependencies.
The `branch` field is actually supported already by [upstream git itself](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-set-branch-b--branchltbranchgt--ltpathgt).
The `tag` field is my invention and my tool may be using it to do semver updates based on the tag name and available upstream tags.
I'm not convinced the tag needs to be documented here since the commit hash is already in git and it possible to map that back to tags.  I've removed `tag` from the PR for now till I'm convinced it needs to be in the file.

Annotate .gitmodules with branch and tag

---

docs.md

Some libuv filesystem functions expect the numeric `mode` argument to be an octal representation of the equivalent `chmod(1)` mode. This is potentially surprising behaviour to anyone who hasn't used either `libuv` or `glibc` from C. The documentation for e.g. `fs_mkdir` in libuv defers to `mkdir(2)` which defers to `mode_t(3)` which only says "It is an integer type". Furthermore, `fs_access` uses a different `mode` type, validated using
[luv_check_amode](https://github.com/luvit/luv/blob/7233e6dea92498a244feb51b790c1ba51e8abbff/src/fs.c#L184), which can accept strings ("symbolic mode" in `chmod(1)`). I chose not to mention that this one still technically accepts an integer because I have no idea about the restrictions of said integer.

docs: Clarify types for mode arg in some filesystem functions

---

tests/test-udp.lua

I have checked `libuv/src/unix/udp.c` and `libuv/src/unix/darwin.c`, can't point out the immediate cause of `EBUSY` when call `uv_udp_set_source_membership`.
I have check open, bind, setsockopt,..., the return code not  mention `EBUSY`.
I checked https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/intro.2.html get  some thing about EBUSY. That means Resource busy.  An attempt to use a system resource which was in use at the time in a manner which would have conflicted with the request. So we do some retry should be safe and can fix and close #704.

ci: handle EBUSY for udp

---

.github/workflows/ci.yml

Closes #709.
This sets our Lua version to the proper 5.4.7 commit/tag and updates calls to `collectgarbage` to use the `incremental` option instead of the deprecated `setpause` and `setstepmul` options. This change should be valid for all 5.4 versions, but not prior versions and not LuaJIT.

Lua 5.4.7 update

---

docs.md
src/constants.c

Partially addresses #711.
This adds a Constants documentation section that explicitly mentions the `uv.constants` table. Due to minor inconsistencies in the way constants are used and exposed across the library, I've limited this section to only include constants that are both defined in `uv.constants` and have lowercase option strings somewhere in luv:
- Address Families
- Signals
- Socket Types
- TTY Modes
I also linked the rest of the docs back to this new section where appropriate, tweaked some of the rhetoric in the Error Handling section, and renamed "signum" to "signame".
Distantly related: #399, #400, #409, #472.

Clean up and expand docs for constants/options

---

src/misc.c

Follow up to @truemedian's comments in https://github.com/luvit/luv/pull/717

Remove unnecessary allocation from wtf8 functions

---

tests/test-tty.lua

While looking into the Valgrind/assertion failure, I noticed the following message being output:
> skip, not on linux or macos
I found this puzzling as I'm actually on Linux. The message also appears in CI workflows using the `ubuntu-latest` image.
A brief investigation yielded that the [early exit in test-tty.lua](https://github.com/luvit/luv/blob/9299a4b211537a82719ada35c045891089eb8b33/tests/test-tty.lua#L2-L11) is faulty; it expects the second `pcall` return value to be `nil`, but in this case it's the typical `module 'ffi' not found` error (that is, a `string` value).
The `ffi` module isn't found because the valgrind workflow only builds PUC Lua and uses that to run the tests. Seeing how there's conditional logic/`cdef` uses here, it may be worth running valgrind + tests with both …

Fix a misleading skip message in test-tty.lua

---

src/luv.c
tests/test-coroutines-require.lua

If the library is opened from a Lua thread (coroutine) that is not the main one, the stored L would be to that thread, which may become suspended (by calling yield). It is unsafe to call functions on suspended Lua threads, which luv does a lot (the stored L is used for callbacks).
The main thread of a Lua state can never yield, so it is always safe to call callbacks on.
This commit ensures the main thread is stored in the luv context instead of the current thread, when we are able to calculate it (LUA_RIDX_MAINTHREAD was added in Lua 5.2, and I have not found a way to determine the main thread in Lua 5.1).
This fixes https://github.com/luvit/luv/issues/503

Use main thread of current Lua state for callbacks, when known

---

CMakeLists.txt

This is to prevent the following warning:
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.

Update minimum cmake version to 3.10

---

src/loop.c

As documented, uv_run is NOT re-entrant and this
prevents this from happening by returning fail.
Each lua state has its own uv loop, so the only
way for this to happen is for uv.run to be called
from a libuv callback.

fix: prevent calling uv.run while already running.

---

src/luv.c
src/test.c

atexit may be called after luv is unloaded and will segfault.
Associated https://github.com/luvit/luv/issues/712

move luv_work_cleanup into loop gc

---

docs.md
tests/test-misc.lua

Addresses part of https://github.com/luvit/luv/issues/751

test-misc: Allow big endian WTF-16, too

---

src/luv.c
src/work.c

Moves work vm storage into a garbage collected userdata. Allowing for each lua state to manage its own storage. This completely removes the need for a global array of work vms.
Better than #755 because it does not introduce an extra interface that integrators have to deal with.
Essentially an expansion of #756 by using the userdata object to store the entire vm array.
In particular, this should mimic pre loop `__gc` behavior of multiple lua states having access to a pool of work vms and that pool being cleaned up automatically everywhere; the existing loop `__gc` does not handle this case well, particularly when one state is closed first (the other state may then attempt to use closed lua states).
Fixes #754

rework luv work vm storage into userdata

---

.gitattributes
docgen.lua
docs.lua
docs.md

This change introduces the files `docs.lua` and `docgen.lua`
which are used to generate `docs.md`.
`docs.lua` use a bespoke format designed so it can emit the `docs.md`
as close to the original version.
`docgen.lua` takes `docs.lua` as an input an emits `docs.md`.
To regenerate the `docs.md`, simply run `lua docgen.lua`.
Closes #632

feat(doc): move to structured format

---

.gitattributes
docgen.lua
docs.lua
docs.md
meta.lua

This file adds additional logic to `docgen.lua` to generate a file `meta.lua` which is formatted with LuaCATs.
For complex types, the script will automatically create either a `@class` or `@alias`, and will be rendered near to their use.
---
Note: This PR produces something similar to https://github.com/LuaCATS/luv, but not 100%. The main difference being that this PR generates significantly less `@class` and `@alias` names.

feat(doc): generate meta file

---

src/thread.c

There are two separate changes here:
- A fix for the use-after-free
- A workaround for a possible Lua bug regarding luaL_Buffer stack usage
See the individual commits for the details.
Closes #751

Fix use-after-free in `new_thread`

---

docs/docs.lua
docs/docs.md
docs/meta.lua
src/luv.c
src/synch.c
src/thread.c
tests/test-thread.lua

Adds a binding to the uv_sem_t interface to allow properly synchronizing thread-related functions across threads.
Fixes #730

feat: add binding for semaphore to test synchronization

---

docs/docgen.lua
docs/meta.lua

Fixes incorrect uv.fs_opendir documentation. It seem to be the only luv function where the optional callback is not at the end of the signature, so the callback param was incorrectly omitted before.

docs: document nil callback when needed
