deps/uv.cmake

bumped libuv version to remove non portable non posix code.
added in build rules specifically for SunOS systems.

Fix building on SunOS systems.

---

examples/cqueues-main.lua
examples/cqueues-slave.lua

Hey Tim,
I thought it might be nice to show how different main loops can work together.
This PR contains two new examples demonstrating how to integrate with [cqueues](http://25thandclement.com/~william/projects/cqueues.html)

Add examples for integrating luv with cqueues

---

src/luv.h

thanks to @brimworks
fixes #153

fix(fs_lstat): enable S_IFLNK

---

src/luv.c
src/poll.c

add new_socket_poll method

---

CMakeLists.txt

Fixes issue https://github.com/luvit/luvi/issues/93

Install header files for shared and static builds

---

README.md

Some build option were introduced in the meantime. Document them to help me to remember what each options does.
Also add note about support for Lua 5.3

README: Add build options

---

src/thread.c
src/work.c
tests/test-thread.lua
tests/test-work.lua

1. support entry_code reuse, reduce loadstring times
2. fix bug create uv_key_t to hold lua vm
3. fix bug when threadpool(uv.new_work) use wrong stack index

enhance threadpool and bug fix

---

src/work.c

solve below problem
out of work scope, which could be gc, but queued jobs not done
the patch prevent it be gc until all queued jobs done.
```lua
test('threadpool', function()
function a(...) return ... end
function b(...) print( ... ) end
local work = thread.work(
a,
b
)
work:queue(2,2)
work:queue(2)
work:queue(2)
end)
```

make luv_work_ctx gc after all queued job done.

---

.travis.yml
src/luv.c
tests/test-sigchld-after-lua_close.sh

Add a test that reproduces #193 and a fixup for @e1ca98c

Setup a proper gc fixup

---

.travis.yml
src/luv.c
tests/test-sigchld-after-lua_close.sh

gc: setup a proper gc for the uv_loop

---

src/async.c
src/check.c
src/fs_event.c
src/fs_poll.c
src/handle.c
src/idle.c
src/lhandle.c
src/lhandle.h
src/lthreadpool.h
src/luv.c
src/pipe.c
src/poll.c
src/prepare.c
src/process.c
src/signal.c
src/stream.c
src/tcp.c
src/thread.c
src/timer.c
src/tty.c
src/udp.c
src/work.c
tests/test-async.lua

try to solve #182 and #184
1. use boxporinter will make pass userdata to thread easy.
2. luv_handle_t add extra field to hold application data.
and any advice are welcome.

support pass async to child threads

---

src/misc.c

This patch will add missed netmask field in network interface.

Add missed netmask filed in network interface

---

appveyor.yml

Solution as suggested in http://help.appveyor.com/discussions/problems/4031-same-code-in-two-repositories-build-passes-in-one-repo-but-fails-in-the-other

Fix AppVeyor on Pro environment

---

src/async.c
src/check.c
src/dns.c
src/fs.c
src/fs_event.c
src/fs_poll.c
src/handle.c
src/idle.c
src/lhandle.c
src/loop.c
src/lreq.c
src/luv.c
src/pipe.c
src/poll.c
src/prepare.c
src/process.c
src/req.c
src/signal.c
src/stream.c
src/tcp.c
src/thread.c
src/timer.c
src/tty.c
src/udp.c
src/work.c

Because I've compiled my lua as c++, I need to compile luv as c++ too. So I've fixed all the compilation problems with c++/ansi c compiler.
Just run ``gcc -ansi -Wall -c src/luv.c -Ideps/libuv/include`` , you can see current compile errors.

compile in ansi mode

---

src/luv.c

Just realize my last pull request contains two lines not intent to be merged.

remove code not intend to be merged.

---

src/handle.c

compile use VS2008

---

src/handle.c
src/lhandle.c

Cleans up the other places that do a dereference of the userdata

fix other userdata casts

---

examples/uvbook/pipe-echo-client.lua
examples/uvbook/pipe-echo-server.lua

This is an luv implementation of the libuv book example for [pipes](https://nikhilm.github.io/uvbook/processes.html#pipes).

examples: add pipe echo example

---

tests/test-tcp.lua

(needed for Travis tests which seem to have broken ipv6 support)
Fixes the Travis failures happening in #267 (but that are unrelated to #267).
EDIT: Relevant Travis issue: https://github.com/travis-ci/travis-ci/issues/8693

Tolerate failure on ipv6 tcp server test and add ipv4 version

---

src/fs.c
src/luv.c
src/luv.h
src/misc.c
src/process.c

add new API and fix minor warning

---

src/luv.c
src/misc.c

update libuv to 1.18.0 and add uv_os_getpid support

update libuv to 1.18.0 and add uv_os_getpid support

---

deps/luajit.cmake

Make ci pass, fix https://travis-ci.org/luvit/luv/jobs/374711139#L103

Update luajit.cmake to support luajit HEAD

---

.travis.yml

As discussed here: https://github.com/luvit/luv/issues/297#issuecomment-410391018
Confirmed to fix the travis builds: https://travis-ci.org/squeek502/luv/builds/411939551

Fix travis libuv.a path (#297)

---

Makefile

Should fix Luarocks build error reported here: https://github.com/luvit/luv/issues/275#issuecomment-413751038

Include deps/lua-compat-5.3 in luarocks .tar.gz

---

src/luv.c
src/misc.c
tests/test-misc.lua

* update libuv to 1.25.0
* unix,win: add uv.os_uname()
* fix minor code style

Update libuv to 1.25.0

---

src/async.c
src/check.c
src/dns.c
src/fs.c
src/fs_event.c
src/fs_poll.c
src/handle.c
src/idle.c
src/lhandle.c
src/lhandle.h
src/lreq.c
src/lreq.h
src/luv.c
src/luv.h
src/poll.c
src/prepare.c
src/process.c
src/signal.c
src/stream.c
src/tcp.c
src/timer.c
src/udp.c

use luv_req_t and luv_handle_t struct filed to hold lua_State pointer,
uv_loop_t data filed may be used by outside of luv
Ref discuss of https://github.com/luvit/luv/pull/325

Refactoring the code to get the loop

---

tests/test-misc.lua

Fix inconsistent assert in gettimeofday test

---

src/async.c
src/check.c
src/dns.c
src/fs.c
src/fs_event.c
src/fs_poll.c
src/handle.c
src/idle.c
src/lhandle.c
src/lhandle.h
src/loop.c
src/lreq.c
src/lreq.h
src/luv.c
src/luv.h
src/poll.c
src/prepare.c
src/process.c
src/signal.c
src/stream.c
src/tcp.c
src/timer.c
src/udp.c
src/work.c
tests/test-coroutines.lua

* Implement support for external uv_loop_t, many thanks to @andreypopp
* fix #244

Implement support for external uv_loop_t

---

src/async.c
src/check.c
src/dns.c
src/fs.c
src/fs_event.c
src/fs_poll.c
src/handle.c
src/idle.c
src/lhandle.c
src/lhandle.h
src/lreq.c
src/lreq.h
src/luv.c
src/luv.h
src/misc.c
src/pipe.c
src/poll.c
src/prepare.c
src/process.c
src/signal.c
src/stream.c
src/tcp.c
src/timer.c
src/tty.c
src/udp.c

This is sub jobs of https://github.com/luvit/luv/issues/336.
With this PR, test of https://github.com/luvit/luv/pull/331#pullrequestreview-245762788
from 0.849045 to 0.773922

Speed up by reduce regristry table queries

---

src/lhandle.c
src/lhandle.h
src/loop.c
src/lreq.c
src/luv.c
src/luv.h
src/thread.c
src/work.c
tests/test-work.lua

An alternative way to achieve https://github.com/luvit/luv/pull/345

support custom/external event callback

---

tests/test-dns.lua

Matches the allowed errors in gnulib's test-getaddrinfo.c:
http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=tests/test-getaddrinfo.c;hb=0b40814b815c65cf56f0938d27499d7962aac640#l90
Addresses https://github.com/luvit/luv/issues/340#issuecomment-507950881

Allow certain error codes in test-dns.lua tests

---

src/luv.h

close https://github.com/luvit/luv/issues/358

fix incorrect macro luv_state

---

README.md
lgtm.yml

lgtm state will change in 24 hours.

add lgtm.yml and update readme.md

---

.ci/install.bat
.ci/setup_lua.sh
.travis.yml
appveyor.yml

Debugging issues with LuaRocks upgrade with Neovim (https://github.com/neovim/neovim/pull/10292).

Test with LuaRocks 3.1.3

---

lgtm.yml

See https://github.com/luvit/luv/pull/367#issuecomment-517863115

lgtm.yml: classify deps as library files

---

.ci/make_rockspec.sh

Include libluv.pc.in in release .tar.gz

---

src/fs.c
src/lhandle.h
src/luv.c
src/misc.c
src/tcp.c
tests/test-fs.lua
tests/test-misc.lua
tests/test-tcp.lua

update libuv to 1.32.0

---

src/luv.c

Fix loop __gc not being called

---

src/lthreadpool.h
src/work.c
tests/test-work.lua

1. reuse cached lua_State for thread pool work scheduling
2. lua_State for thread pool can be gc

Optimize threadpool implementation

---

src/luv.c
src/stream.c
src/tcp.c

Add binding for uv_stream_get_write_queue_size

---

src/fs.c
src/luv.c

Add binding for uv_fs_lchown

---

tests/test-process.lua

This is one way to address https://github.com/luvit/luv/issues/421
Instead of relying on `uv.exepath()` to be a standard Lua interpreter that always reacts the same way to `-e` and `-` arguments, this instead spawns processes that should be as consistent, but allows the tests to be run from anywhere (like the shim in #421).
This is currently incomplete, as `test-signal` still relies on `uv.exepath()` being a standard Lua interpreter.

test-process: Make tests not depend on uv.exepath() being a Lua interpreter

---

.travis.yml

Use Ubuntu 18.04 in Valgrind job to get more recent Valgrind

---

.travis.yml

Accidentally removed Luarocks installation from the deploy step in https://github.com/luvit/luv/pull/432

travis: Fix deploy step

---

src/async.c
src/handle.c
src/lthreadpool.h
src/thread.c
src/work.c

this will speed up pass string to threadpool

Optimize data exchange between threads

---

src/async.c
src/handle.c
src/lhandle.c
src/lhandle.h

other clibs can manage how to gc extra data in luv_handle_t

Handle luv_handle_t extra be gc correctly

---

docs.md

Continuing from #409, this adds documentation for function parameters (including callbacks) and cleans up some loose ends.

Parameter documentation

---

src/constants.c

update libuv to 1.37.0

---

docs.md
src/luv.c
src/pipe.c
tests/test-pipe.lua

pipe: Add pipe_chmod binding

---

docs.md
src/luv.c
src/process.c
tests/test-process.lua

process: Add process_get_pid binding

---

CMakeLists.txt

Try to install luv.so for luajit-2.1
before:
-- Installing: /usr/local/lib/lua/./luv.so
After:
-- Installing: /usr/local/lib/lua/5.1/luv.so

fix install path when `make install`

---

src/process.c

This is one possible fix for the process bug in https://github.com/luvit/luv/issues/510. One other way to fix it would be to just leave the args strings on the stack instead of popping them off. Not sure which is better.

Fix args potentially being garbage collected before use in luv_spawn

---

README.md

In https://github.com/luvit/luv/pull/515 our Lua verison in `deps` got updated to 5.4. This just updates the readme accordingly.

readme: Update for Lua 5.4

---

tests/test-udp.lua

Fix udp multicast test when no exernal interfaces are available

---

tests/test-udp.lua

Fix udp multicast test with restrictive firewall settings

---

CMakeLists.txt

Changes:
* Install pkgconfig file.
* Install shared library in binary folder.
* Fix shared library name.

cmake: Fix install files in mingw

---

src/handle.c
src/stream.c

This was something I needed to figure out when looking into #601 and thought that a comment would be helpful in the future, as it was fairly non-trivial to understand.

Add comments to `luv_check_{handle,stream}` explaining how they work

---

src/fs.c
tests/test-fs.lua

fix: avoid `dir` be gc early.

---

tests/test-udp.lua

Disable flaky UDP test on macOS CI

---

.ci/check_docs.sh
.github/workflows/ci.yml
docs.lua

Just to ensure we don't accidentally manually edit `docs.md` and forget to update `docs.lua`

ci: Add check that docs.md and meta.lua are up-to-date

---

src/handle.c

Last usage was removed in ff5e90249e08471396f73f599edcdfe405ac4e6e (#654)
Closes #771

Remove unused function luv_gc_cb
